// src/router.tsx
import { createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen' // auto-generated by TanStack Router CLI

export const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
  defaultStaleTime: 30_000,
})

// Type registration for useNavigate, Link, etc.
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
